site_name: Documentation for seed-Kraken
repo_url: https://github.com/macieksk/seed-kraken
site_author: Maciek Sykulski macieksk@gmail.com
theme: cosmo
docs_dir: .
markdow_extensions: [smartypants]
pages:
- [index.md, Home]
- [example.md, Example Run]
- [installation.md, Installation]
- [about.md, About]
